server:
  port: 8081

spring:
  application:
    name: project-user
  datasource:
    url: jdbc:mariadb://${MARIADB_HOST:mariadb}:3306/${MARIADB_DATABASE:project_user}
    username: ${MARIADB_USER:appuser}
    password: ${MARIADB_PASSWORD:app_pass_123!}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

jwt:
  secret: ${JWT_SECRET:change-me}
  access-token-validity-seconds: ${JWT_ACCESS_TTL:3600}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://sc-eureka:8761/eureka}
  instance:
    prefer-ip-address: true
    # 필요 시 고정 호스트명 지정
    # hostname: ${HOSTNAME:sc-user-svc}
