server:
  port: 8081

spring:
  application:
    name: project-user   
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/project_user
    username: appuser
    password: app_pass_123!
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: change-me
  access-token-validity-seconds: 3600

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
